Skills are finished
IamMarkanditsgood/UnderWorld pull request #8
Opened 2023-10-24 16:10 UTC by IamMarkanditsgood

just left to make effects and realize some functions for damage

2023-10-24 19:35 UTC, SAShamark requested changes
1) 
Гілка неправильно названа, слідкуй за цим
feature/CVSF-15-character-skills
Вже можеш не міняти
2)
Багато проблем з відступами, слідкуй за цим

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Character/Skills/Dictionaries/SkillDictionaries.cs
і ти можеш писати так
public Dictionary<SkillTypes, SkillObjectConfig> BulletConfig { get; set; } = new()
        {
        ...
        }

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Character/Skills/CharacterSkills/ShootSkills/Fireball.cs
>  using UnityEngine;
Цей клас теж не юзається

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Character/Skills/CharacterSkills/ShootSkills/AimRockets.cs
> +    public class AimRockets : ISkillUsable
Можна заюзати дженеріки і позбутись дублікації подібних класів як: Arrow, QuantumBall ...

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Character/Skills/CharacterSkills/MainSkills/TimeStopper.cs
> +    public class TimeStopper : MonoBehaviour, ISkillUsable, IDisposable
Норм що ти вивчив асинхронність, але монобех класи краще робити з корутинами, бо корутини залежать від життєвого циклу сутності.
Варто почитати про різницю асинхронності і корутин

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Character/Skills/CharacterSkills/MainSkills/Teleport.cs
> +        public void UseSkill(GameObject character,SkillDictionaries skillDictionaries, SkillsConfig skillConfig)
Дивно що для телепорта потрібен Rigidbody

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Character/Skills/CharacterSkills/MainSkills/Teleport.cs
> +        public void UseSkill(GameObject character,SkillDictionaries skillDictionaries, SkillsConfig skillConfig)
Чому не написати просто character.transform. position = newPosition?

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Character/Skills/CharacterSkills/MainSkills/SuperKiller.cs
> +        public void UseSkill(GameObject character, SkillDictionaries skillDictionaries, SkillsConfig skillConfig)
Ти багато де не юзаєш параметри, просто переоприділи декілька варіантів UseSkill
public void UseSkill(GameObject character, SkillDictionaries skillDictionaries, SkillsConfig skillConfig);
public void UseSkill(SkillDictionaries skillDictionaries, SkillsConfig skillConfig);
public void UseSkill();

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Character/Skills/CharacterSkills/MainSkills/Shield.cs
> +    public class Shield : ISkillUsable, IDisposable
ще 1 дублікат

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Character/Character.cs
> +            _inputController.OnShiftPressed -= () => _skillsManager.UseMainSkill(_characterBody);
Підписувати та відписуватись через лямбду не можна, буде помилка
Event unsubscription via anonymous delegate

Роби так:
private void OnDestroy()
        {
            _inputController.OnShiftPressed -= OnUseMainSkill;
}
private void OnUseMainSkill()=> _skillsManager.UseMainSkill(_characterBody);

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Character/Character.cs
> +            _inputController.OnShiftPressed += () => _skillsManager.UseMainSkill(_characterBody);
З підпискою як і з відпискою

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Character/Character.cs
> +        [SerializeField] private GameObject _vortex;
Чому одразу їх класи не отримуєш?
[SerializeField] private Shield _shield;

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Bullets/SkillObjectConfig.cs
> +        [SerializeField] private GameObject _sound;
Звук і гейм обджект, дивно

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Bullets/Shoot.cs
> +            Transform bulletPos = character.GetComponent<Character.Character>().ShootingSkillPos;// change alhoritm
Що за коміт, він навіть не зрозумілий, удаляй

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Bullets/Bullet.cs
> +            _bulletMover.Move(gameObject, _skillObjectConfig.Speed );
Ти рухаєш об'єкти не через фізику, то чому FixedUpdate а не update?

2023-10-24 19:35 UTC, SAShamark commented on Assets/Scripts/GamePlay/Bullets/Bullet.cs
> +    public class Bullet : MonoBehaviour
Реалізуй тут IBulletMovable
Зроби тут:
public virtual void Move()
        {
            gameObject.transform.Translate(Vector3.forward * _skillObjectConfig.Speed* Time.deltaTime);
        }
        І наслідуй AimedBullet від цього Bullet щоб оверайднути метод Move

2023-10-25 16:01 UTC, IamMarkanditsgood commented on Assets/Scripts/GamePlay/Character/Character.cs
> +        [SerializeField] private GameObject _vortex;
тому що там немає скриптів. Я просто вмикаю і вимикаю обєкт

2023-10-25 16:02 UTC, IamMarkanditsgood commented on Assets/Scripts/GamePlay/Bullets/SkillObjectConfig.cs
> +        [SerializeField] private GameObject _sound;
Це я потім буду робити звуки а поки це заглушка

2023-10-25 16:03 UTC, IamMarkanditsgood commented on Assets/Scripts/GamePlay/Bullets/Shoot.cs
> +            Transform bulletPos = character.GetComponent<Character.Character>().ShootingSkillPos;// change alhoritm
Це я собі залишив на потім. Але забув

2023-10-25 18:13 UTC, SAShamark commented on Assets/Scripts/GamePlay/Bullets/SkillObjectConfig.cs
> +        [SerializeField] private GameObject _sound;
Погана практика!
До того ж в задачі нічого не сказано про звуки
Уяви що ти в команді працюєш, тому все має бути по задачам!

2023-10-25 18:14 UTC, SAShamark commented on Assets/Scripts/GamePlay/Bullets/Shoot.cs
> +            Transform bulletPos = character.GetComponent<Character.Character>().ShootingSkillPos;// change alhoritm
А туду для чого?

2023-10-25 18:36 UTC, SAShamark requested changes

2023-10-25 18:36 UTC, SAShamark commented on Assets/Scripts/GamePlay/Character/Skills/Interface/ISkillUsable.cs
Для скілів як і для переміщення варто зробити базовий скіл, де ти зможеш зробити наприклад кулдавн.
Або ти в майбутньому захочеш зробити скіл по натисненню і по тоглу, тоді взагалі буде шик

2023-10-26 15:02 UTC, IamMarkanditsgood commented on Assets/Scripts/GamePlay/Character/Skills/Dictionaries/SkillDictionaries.cs
Вони там і є. Просто вони переносяться сюди щоб їх можна було міняти під час гри

2023-10-26 15:04 UTC, IamMarkanditsgood commented on Assets/Scripts/GamePlay/Character/Skills/CharacterSkills/SupportSkills/Vortex.cs
> +                await ShieldTimer(_cancellationTokenSource.Token);
Ти так сказав зробити щоб помилки вибивало вроді

2023-10-26 15:04 UTC, IamMarkanditsgood commented on Assets/Scripts/GamePlay/Character/Skills/CharacterSkills/SupportSkills/Vortex.cs
> +                await ShieldTimer(_cancellationTokenSource.Token);
Але я приберу

2023-10-26 15:08 UTC, IamMarkanditsgood commented on Assets/Scripts/GamePlay/Character/Skills/CharacterSkills/SupportSkills/Vortex.cs
> +    public class Vortex : ISkillUsable
Я вже казав за те що я наперед розробив скіли всі. Він буде в магазині юзатись

2023-10-26 15:16 UTC, IamMarkanditsgood commented on Assets/Scripts/GamePlay/Character/Skills/CharacterSkills/SupportSkills/Vortex.cs
> +            if (!_inUse)
Взагалі in use звучить краще при перекладі але я виправлю. Доречі тут можна смійли ставити?

2023-10-26 15:27 UTC, IamMarkanditsgood commented on Assets/Scripts/GamePlay/Character/Skills/CharacterSkills/MainSkills/Teleport.cs
> +        public void UseSkill(GameObject character,SkillDictionaries skillDictionaries, SkillsConfig skillConfig)
Це тому що мені треба телепортувати за напрямком руху, а для цього треба  Rigidbody щоб дізнатись напрямок

2023-10-26 15:28 UTC, IamMarkanditsgood commented on Assets/Scripts/GamePlay/Character/Skills/CharacterSkills/MainSkills/Teleport.cs
> +        public void UseSkill(GameObject character,SkillDictionaries skillDictionaries, SkillsConfig skillConfig)
character.transform. position = newPosition? Буде просто переносити куди завгодно. Тай newPosition треба десь взяти а у мене це напрямок руху + телепорт на n-ну відстань

2023-10-29 09:11 UTC, SAShamark approved these changes

2023-10-29 09:11 UTC, SAShamark commented on Assets/Scripts/GamePlay/Entities/Character/Skills/CharacterSkills/MainSkills/SuperKiller.cs
> +            /*GameObject obj = _enemy.Spawn("Standart", transform.forward).gameObject;
чи потрібен цей коміт?

2023-10-29 09:11 UTC, SAShamark commented on Assets/Scripts/GamePlay/Level/ObjectContainer.cs
Думаю цей клас можна видалити

2023-10-29 20:26 UTC, merged